### ISSUE TITLE
[Bug] When the output format of AWS CLI is set to 'table', kubectl will encounter an error when connecting to the EKS created by eksctl

### ISSUE THREAD

**Issue by glongzh** [weaveworks/eksctl#6547]
### What were you trying to accomplish?
`eksctl create cluster -f test.yml`

### What happened?
At the end of the EKS creation, the following error is displayed:
```bash
2023-04-20 09:16:38 [✖️]  unable to use kubectl with the EKS cluster (check 'kubectl version'): WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Unable to connect to the server: getting credentials: decoding stdout: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
kubectl cannot connect to eks.

### How to reproduce it?

set the output to `table` when `aws configure`, and create an eks using eksctl

**Anything else we need to know?**
eksctl should set the output format to `json` in the aws command line when generating `~/.kube/config` instead of relying on the user's AWS profile configuration, which would be a better solution.

**Comment by yuxiang-zhang** [comment]
Hi, may I know the version of AWS CLI you are using? There were similar known issues in AWS CLI which were fixed recently, could you try updating the AWS CLI version and re-run `eks update-kubeconfig`?

**Comment by glongzh** [comment]
@yuxiang-zhang 
The version of aws cli is 2.11.10.
Yes, I know I can run `aws eks update-kubeconfig` to update the kubeconfig, and it works because aws cli create another context which sets ` --output json` option. But the context eksctl created still cannot work. 
Thanks.

**Comment by yuxiang-zhang** [comment]
Thank you a ton, that makes sense. I'll open a PR for the fix
